In [1]:
import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib as plt

In [2]:
Data=pd.read_csv('Desktop/DATA TYPES/heart_statlog_cleveland_hungary_final.csv')

In [3]:
Data.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  \
0            0             172                0      0.0         1   
1            0             156                0      1.0         2   
2            1              98                0      0.0         1   
3            0             108                1      1.5         2   
4            0             122                0      0.0         1   

   Heart disease  
0              0  
1              1  
2              0  
3              1  
4              0

In [4]:
Data.head()

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   
1   49    0                3           160          180                    0   
2   37    1                2           130          283                    0   
3   48    0                4           138          214                    0   
4   54    1                3           150          195                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  \
0            0             172                0      0.0         1   
1            0             156                0      1.0         2   
2            1              98                0      0.0         1   
3            0             108                1      1.5         2   
4            0             122                0      0.0         1   

   Heart disease  
0              0  
1              1  
2              0  
3              1  
4              0

In [5]:
Data.shape

(1190, 12)

In [6]:
Data.describe()

age          sex  chest pain type  resting bp s  cholesterol  \
count  1190.000000  1190.000000      1190.000000   1190.000000  1190.000000   
mean     53.720168     0.763866         3.232773    132.153782   210.363866   
std       9.358203     0.424884         0.935480     18.368823   101.420489   
min      28.000000     0.000000         1.000000      0.000000     0.000000   
25%      47.000000     1.000000         3.000000    120.000000   188.000000   
50%      54.000000     1.000000         4.000000    130.000000   229.000000   
75%      60.000000     1.000000         4.000000    140.000000   269.750000   
max      77.000000     1.000000         4.000000    200.000000   603.000000   

       fasting blood sugar  resting ecg  max heart rate  exercise angina  \
count          1190.000000  1190.000000     1190.000000      1190.000000   
mean              0.213445     0.698319      139.732773         0.387395   
std               0.409912     0.870359       25.517636         0.487360   
min               0.000000     0.000000       60.000000         0.000000   
25%               0.000000     0.000000      121.000000         0.000000   
50%               0.000000     0.000000      140.500000         0.000000   
75%               0.000000     2.000000      160.000000         1.000000   
max               1.000000     2.000000      202.000000         1.000000   

           oldpeak     ST slope  Heart disease  
count  1190.000000  1190.000000    1190.000000  
mean      0.922773     1.624370       0.528571  
std       1.086337     0.610459       0.499393  
min      -2.600000     0.000000       0.000000  
25%       0.000000     1.000000       0.000000  
50%       0.600000     2.000000       1.000000  
75%       1.600000     2.000000       1.000000  
max       6.200000     3.000000       1.000000

In [7]:
Data.dropna()

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
...   ...  ...              ...           ...          ...   
1185   45    1                1           110          264   
1186   68    1                4           144          193   
1187   57    1                4           130          131   
1188   57    0                2           130          236   
1189   38    1                3           138          175   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0             172                0   
1                       0            0             156                0   
2                       0            1              98                0   
3                       0            0             108                1   
4                       0            0             122                0   
...                   ...          ...             ...              ...   
1185                    0            0             132                0   
1186                    1            0             141                0   
1187                    0            0             115                1   
1188                    0            2             174                0   
1189                    0            0             173                0   

      oldpeak  ST slope  Heart disease  
0         0.0         1              0  
1         1.0         2              1  
2         0.0         1              0  
3         1.5         2              1  
4         0.0         1              0  
...       ...       ...            ...  
1185      1.2         2              1  
1186      3.4         2              1  
1187      1.2         2              1  
1188      0.0         2              1  
1189      0.0         1              0  

[1190 rows x 12 columns]

In [8]:
Data.isnull()

age    sex  chest pain type  resting bp s  cholesterol  \
0     False  False            False         False        False   
1     False  False            False         False        False   
2     False  False            False         False        False   
3     False  False            False         False        False   
4     False  False            False         False        False   
...     ...    ...              ...           ...          ...   
1185  False  False            False         False        False   
1186  False  False            False         False        False   
1187  False  False            False         False        False   
1188  False  False            False         False        False   
1189  False  False            False         False        False   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                   False        False           False            False   
1                   False        False           False            False   
2                   False        False           False            False   
3                   False        False           False            False   
4                   False        False           False            False   
...                   ...          ...             ...              ...   
1185                False        False           False            False   
1186                False        False           False            False   
1187                False        False           False            False   
1188                False        False           False            False   
1189                False        False           False            False   

      oldpeak  ST slope  Heart disease  
0       False     False          False  
1       False     False          False  
2       False     False          False  
3       False     False          False  
4       False     False          False  
...       ...       ...            ...  
1185    False     False          False  
1186    False     False          False  
1187    False     False          False  
1188    False     False          False  
1189    False     False          False  

[1190 rows x 12 columns]

In [9]:
Data.count()

age                    1190
sex                    1190
chest pain type        1190
resting bp s           1190
cholesterol            1190
fasting blood sugar    1190
resting ecg            1190
max heart rate         1190
exercise angina        1190
oldpeak                1190
ST slope               1190
Heart disease          1190
dtype: int64

In [10]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

In [11]:
X, y = Data.drop(columns=['Heart disease']), Data['Heart disease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
np.array(X_test)

array([[61. ,  1. ,  4. , ...,  0. ,  1. ,  2. ],
       [54. ,  1. ,  3. , ...,  1. ,  1.5,  2. ],
       [55. ,  0. ,  2. , ...,  0. ,  0. ,  1. ],
       ...,
       [55. ,  0. ,  2. , ...,  0. ,  1.4,  2. ],
       [43. ,  1. ,  4. , ...,  1. ,  2. ,  2. ],
       [55. ,  1. ,  4. , ...,  1. ,  1.7,  3. ]])

In [13]:
np.array(y_test)

array([1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1], dtype=int64)

In [14]:
import warnings
warnings.filterwarnings(action="ignore")

In [15]:
model= RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [16]:
import pickle

# Save the model to a file
with open('cardiovascular_disease_model.pkl', 'wb') as model_file:
    pickle.dump('cardiovascular_disease_model.pkl', model_file)

In [17]:
# Load the model from the pickle file
with open('cardiovascular_disease_model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

In [18]:
model.score(X_test,y_test)

0.9537815126050421

In [19]:
y_train

1005    1
224     0
798     1
816     1
427     0
       ..
1044    1
1095    0
1130    1
860     1
1126    0
Name: Heart disease, Length: 952, dtype: int64

In [20]:
New_data=([[37,1,4,140,207,0,0,130,1,1.5,2]])

In [21]:
model.predict(New_data)

array([1], dtype=int64)

In [22]:
prediction=model.predict(New_data)


In [23]:
if (prediction[0]==0):
   print('The person does not have heart disease')
else :
   print('The person has heart disease')



The person has heart disease
